### ISSUE TITLE
how about applying to sparse pointcloud?

### ISSUE THREAD

**Issue by mjjdick** [Jia-Research-Lab/PointGroup#1]
Hi, nice work!
I'm just wondering how about your work applying to sparse point cloud such as Velodyne 64? do you do some experiments on those data? If so, I am looking forward to the experiments results!

**Comment by llijiang** [comment]
Hi, I just tested the framework on indoor scenes. You could also try on those data.

**Comment by Xuhy945** [comment]
Hi! Recently, I was training my data in your model. I followed the steps of README. However, an error occurred:
 cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCBlas.cu:259. 
I can't find out what caused this error. Can you give me some help?

**Comment by llijiang** [comment]
> Hi! Recently, I was training my data in your model. I followed the steps of README. However, an error occurred:
> cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCBlas.cu:259.
> I can't find out what caused this error. Can you give me some help?

Hi, I haven't seen this error before. It may relate to the CUDA and Pytorch version. I find some similar issues - [pytorch/pytorch#7548](https://github.com/pytorch/pytorch/issues/7548#issue-322689677) and [pytorch/pytorch#17334](https://github.com/pytorch/pytorch/issues/17334#issue-412707167).

**Comment by carrjp** [comment]
@Xuhy945 Hey, did you find a solution for the error you encountered? I encountered the same issue after following the README and trying to train the network with ScannetV2 data.

**Comment by Xuhy945** [comment]
I had saved this problem. I used the cuda 10.0, instead of cuda 9.0(my GPU is 2080ti). What's more, I added torch.backends.cudnn.enabled = False to the mian of the code, then the code can work.




------------------&nbsp;Original&nbsp;------------------

**Comment by sidml** [comment]
Just putting it out here if anyone else encounters similar issue.
I was getting this error when i tried to run the code 

> CUDA error: an illegal memory access was encountered (copy_kernel_cuda at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/Copy.cu:180)

This error was happening because the batch size in my custom dataloader was different than the batchsize defined in [config file](https://github.com/Jia-Research-Lab/PointGroup/blob/dea7ab1fbe6c2a519a251beac595085295439f77/config/pointgroup_run1_scannet.yaml#L17). So, the solution was to make the batchsize in my custom dataloader same as that of the configuration file (or you can read batch size from config file).
